import { Event } from "@/types/event";

// no images included yet

const mockEvents: Event[] = [
  {
    _id: "event1",
    name: "Summer Vibes Festival",
    organiserId: "organizer1",
    date: new Date("2024-07-12"),
    location: "Los Angeles, CA",
    genre: ["Pop", "EDM"],
    duration: 2,
    maxCapacity: 10000,
    link: "https://summervibesfestival.com",
  },
  {
    _id: "event2",
    name: "Rock Out Loud",
    organiserId: "organizer2",
    date: new Date("2024-09-10"),
    location: "Austin, TX",
    genre: ["Rock"],
    duration: 3,
    maxCapacity: 15000,
    link: "https://rockoutloud.com",
  },
  {
    _id: "event3",
    name: "Indie Nights",
    organiserId: "organizer3",
    date: new Date("2024-06-15"),
    location: "New York, NY",
    genre: ["Indie", "Alternative"],
    duration: 1,
    maxCapacity: 8000,
    link: "https://indienights.com",
  },
  {
    _id: "event4",
    name: "Jazz in the Park",
    organiserId: "organizer1",
    date: new Date("2024-05-22"),
    location: "Chicago, IL",
    genre: ["Jazz", "Blues"],
    duration: 2,
    maxCapacity: 12000,
    link: "https://jazzinthepark.com",
  },
  {
    _id: "event5",
    name: "EDM Blast",
    organiserId: "organizer2",
    date: new Date("2024-11-18"),
    location: "Miami, FL",
    genre: ["EDM", "House"],
    duration: 3,
    maxCapacity: 20000,
    link: "https://edmblast.com",
  },
  {
    _id: "event6",
    name: "Hip-Hop Block Party",
    organiserId: "organizer3",
    date: new Date("2024-08-25"),
    location: "Atlanta, GA",
    genre: ["Hip-Hop"],
    duration: 1,
    maxCapacity: 10000,
    link: "https://hiphopblockparty.com",
  },
  {
    _id: "event7",
    name: "Country Music Jamboree",
    organiserId: "organizer1",
    date: new Date("2024-10-10"),
    location: "Nashville, TN",
    genre: ["Country"],
    duration: 2,
    maxCapacity: 15000,
    link: "https://countrymusicjamboree.com",
  },
  {
    _id: "event8",
    name: "Electronic Sounds Festival",
    organiserId: "organizer2",
    date: new Date("2024-12-05"),
    location: "Berlin, Germany",
    genre: ["Electronic", "Techno"],
    duration: 3,
    maxCapacity: 18000,
    link: "https://electronicsoundsfestival.com",
  },
  {
    _id: "event9",
    name: "Latin Music Extravaganza",
    organiserId: "organizer3",
    date: new Date("2024-06-30"),
    location: "Miami, FL",
    genre: ["Latin", "Reggaeton"],
    duration: 2,
    maxCapacity: 12000,
    link: "https://latinmusicextravaganza.com",
  },
  {
    _id: "event10",
    name: "Metal Mayhem",
    organiserId: "organizer1",
    date: new Date("2024-03-20"),
    location: "London, UK",
    genre: ["Metal", "Hard Rock"],
    duration: 3,
    maxCapacity: 14000,
    link: "https://metalmayhem.com",
  },
];

export default mockEvents;
