export const musicGenres = [
  "Acid techno",
  "Alternative hip hop",
  "Ambient",
  "Bass music",
  "Breakbeat",
  "Chillhop",
  "Chillwave",
  "Deep house",
  "Detroit techno",
  "Disco",
  "Drum and bass",
  "Dub",
  "Dubstep",
  "EDM",
  "Electro house",
  "Electro-industrial",
  "Electropop",
  "Future bass",
  "Future funk",
  "Future house",
  "Garage house",
  "Hardstyle",
  "House",
  "House music",
  "Hyperpop",
  "Industrial",
  "Industrial rock",
  "Jungle",
  "Lofi hip hop",
  "Minimal techno",
  "Progressive house",
  "Progressive trance",
  "Psychedelic trance",
  "Synthwave",
  "Tech house",
  "Techno",
  "Trap (EDM)",
  "Trap",
  "Trance music",
  "Tropical house",
  "Uplifting trance",
  "Vaporwave",
  "Euphoric hardstyle",
  "Eurodance"
];
