export const musicGenres = [
  "Ambient",
  "Chillhop",
  "Bass music",
  "Drum and bass",
  "Future bass",
  "Trap (EDM)",
  "Dubstep",
  "House music",
  "Deep house",
  "Progressive house",
  "Future house",
  "Tech house",
  "Tropical house",
  "Electro house",
  "Techno",
  "Acid techno",
  "Detroit techno",
  "Minimal techno",
  "Trance music",
  "Progressive trance",
  "Psychedelic trance",
  "Uplifting trance",
  "Hardstyle",
  "Euphoric hardstyle",
  "Disco",
  "Electropop",
  "Synthwave",
  "Vaporwave",
  "Chillwave",
  "Lofi hip hop",
  "Alternative hip hop",
  "Hyperpop",
  "Industrial",
  "Electro-industrial",
  "Industrial rock",
  "Future funk",
  "Jungle",
  "Breakbeat",
  "Eurodance",
  "Dub",
  "Garage house"
];
