export const musicGenres = [
  "Ambient",
  "Ambient dub",
  "Dark ambient",
  "Ambient industrial",
  "Dungeon synth",
  "Isolationism",
  "Dreampunk",
  "Illbient",
  "New-age",
  "Neoclassical new-age",
  "Space music",
  "Chillhop",
  "Ambient trance",
  "Bass music",
  "Footwork",
  "Future bass",
  "Kawaii future bass",
  "Jungle terror",
  "Midtempo bass",
  "Future jungle",
  "Drum and bass fusion",
  "Neurostep",
  "Trap (EDM)",
  "UK bass",
  "Wave",
  "Hardwave",
  "Breakbeat",
  "Acid breaks",
  "Baltimore club",
  "Jersey club",
  "Philly club",
  "Big beat",
  "Breakbeat hardcore",
  "Darkcore",
  "Hardcore breaks",
  "Broken beat",
  "Florida breaks",
  "Nu skool breaks",
  "Progressive breaks",
  "Psychedelic breakbeat",
  "Chill-out",
  "Chillstep",
  "Downtempo",
  "Downtempo trance",
  "Psybient",
  "Psydub",
  "Trip hop",
  "Trip rock",
  "Chillgressive",
  "Disco",
  "Nu-funk",
  "Disco funk",
  "Afro/cosmic music",
  "Electro-disco",
  "Hi-NRG",
  "Eurobeat",
  "Eurodance",
  "Italo dance",
  "Italo disco",
  "Spacesynth",
  "Space disco",
  "Eurodisco",
  "Nu-disco",
  "Post-disco",
  "Boogie",
  "City pop",
  "Deep tech",
  "Drum and bass",
  "Darkstep",
  "Drumfunk",
  "Drumstep",
  "Hardstep",
  "Intelligent drum and bass",
  "Atmospheric drum and bass",
  "Jazzstep",
  "Jump-up",
  "Liquid funk",
  "Neurofunk",
  "Sambass",
  "Techstep",
  "Dub",
  "Dub poetry",
  "Dubtronica",
  "Reggae fusion",
  "Future dub",
  "Digital reggae",
  "Electronic rock",
  "Dance-rock",
  "Alternative dance",
  "Baggy",
  "New rave",
  "Dance-punk",
  "Electronic pop",
  "Dance-pop",
  "Freestyle",
  "Disco polo",
  "Hyperpop",
  "Sophisti-pop",
  "Synth-pop",
  "Electroclash",
  "Electropop",
  "Wonky pop",
  "Indietronica",
  "Krautrock",
  "New wave",
  "Cold wave",
  "Dark wave",
  "Neoclassical dark wave",
  "Neue Deutsche Todeskunst",
  "Ethereal wave",
  "Nu-gaze",
  "Minimal wave",
  "Neue Deutsche Welle",
  "New romantic",
  "Post-rock",
  "Space rock",
  "Synth-metal",
  "Electrogrind",
  "Electronicore",
  "Synth-punk",
  "Electronica",
  "Folktronica",
  "Live electronic",
  "Laptronica",
  "Nu jazz",
  "Progressive electronic",
  "Berlin School",
  "Kosmische musik",
  "Ethnic electronica and regional EDM",
  "Asian Underground",
  "African electronic dance music",
  "Afrobeats",
  "Azonto",
  "Coupé-décalé",
  "Kuduro",
  "Mahraganat",
  "Shangaan electro",
  "Budots",
  "Changa tuki",
  "Dancehall pop",
  "Denpa music",
  "Guaracha",
  "Funk carioca",
  "Funk melody",
  "Funk ostentação",
  "Proibidão",
  "Rasteirinha",
  "Merenhouse",
  "Nortec",
  "Rabòday",
  "Rara tech",
  "Russ music",
  "Shamstep",
  "Tecnocumbia",
  "Tribal guarachero",
  "Worldbeat",
  "Manila sound",
  "Experimental electronic",
  "Black MIDI",
  "Deconstructed club",
  "Drone",
  "Electroacoustic music",
  "Acousmatic music",
  "Electroacoustic improvisation",
  "Musique concrète",
  "Soundscape",
  "Glitch",
  "Microsound",
  "Noise music",
  "Danger music",
  "Japanoise",
  "Harsh noise",
  "Harsh noise wall",
  "Power electronics",
  "Death industrial",
  "Power noise",
  "Plunderphonics",
  "Sampledelia",
  "Reductionism",
  "Lowercase",
  "Onkyokei",
  "Funk fusion genres",
  "Acid jazz",
  "Funktronica",
  "Synth-funk",
  "Jungle",
  "Ragga jungle",
  "Hard dance",
  "Hard NRG",
  "Hardstyle",
  "Dubstyle",
  "Euphoric frenchcore",
  "Euphoric hardstyle",
  "Rawstyle",
  "Trapstyle",
  "Jumpstyle",
  "Lento violento",
  "Mákina",
  "Hardcore",
  "Bouncy techno",
  "Breakcore",
  "Raggacore",
  "Digital hardcore",
  "Frenchcore",
  "Gabber",
  "Early hardcore",
  "Mainstream hardcore",
  "Happy hardcore",
  "UK hardcore",
  "Industrial hardcore",
  "J-core",
  "Speedcore",
  "Extratone",
  "Flashcore",
  "Splittercore",
  "Hauntology",
  "Chillwave",
  "Hypnagogic pop",
  "Synthwave",
  "Darksynth",
  "Sovietwave",
  "Vaporwave",
  "Future funk",
  "Hardvapour",
  "Mallsoft",
  "Hip hop fusion genres",
  "Afroswing",
  "Alternative hip hop",
  "Hipster hop",
  "Cloud rap",
  "Crunk",
  "Crunkcore",
  "Snap music",
  "Electro",
  "Emo rap",
  "Glitch hop",
  "Instrumental hip hop",
  "Lofi hip hop",
  "Miami bass",
  "Mumble rap",
  "Trap",
  "Afro trap",
  "Drill",
  "Brooklyn drill",
  "UK drill",
  "Latin trap",
  "Phonk",
  "Drift phonk",
  "Brazilian phonk",
  "Plugg",
  "UK trap",
  "House music",
  "Acid house",
  "Afro house",
  "Afro tech",
  "Amapiano",
  "Kidandali",
  "Ambient house",
  "Balearic beat",
  "Ballroom",
  "Bass house",
  "Brazilian bass",
  "Slap house",
  "Blog house",
  "Chicago hard house",
  "Chicago house",
  "Deep house",
  "Disco house",
  "Diva house",
  "Hardbag",
  "Electro house",
  "Big room house",
  "Future rave",
  "Complextro",
  "Dutch house",
  "Fidget house",
  "Melbourne bounce",
  "Electro swing",
  "Eurohouse",
  "French house",
  "Funky house",
  "Future house",
  "Garage house",
  "Ghetto house",
  "Ghettotech",
  "Juke house",
  "Gqom",
  "Hip house",
  "Electro hop",
  "Italo house",
  "Jackin house",
  "Jazz house",
  "Kwaito",
  "Latin house",
  "Melodic house",
  "Microhouse",
  "Moombahcore",
  "Moombahton",
  "Moombahsoul",
  "New Jersey sound",
  "Outsider house",
  "Lo-fi house",
  "Progressive house",
  "Soulful house",
  "Stadium house",
  "Tech house",
  "Tribal house",
  "Tropical house",
  "Trouse",
  "UK hard house",
  "Pumping house",
  "Hardbass",
  "Scouse house",
  "Industrial and post-industrial",
  "Electro-industrial",
  "Dark electro",
  "Aggrotech",
  "Electronic body music",
  "Futurepop",
  "New beat",
  "Industrial hip hop",
  "Industrial metal",
  "Cyber metal",
  "Neue Deutsche Härte",
  "Industrial rock",
  "Martial industrial",
  "Witch house",
  "Intelligent dance music",
  "Algorave",
  "Drill 'n' bass",
  "R&B and soul fusion genres",
  "Alternative R&B",
  "Contemporary R&B",
  "Neo soul",
  "New jack swing",
  "Techno",
  "Acid techno",
  "Ambient techno",
  "Birmingham sound",
  "Bleep techno",
  "Detroit techno",
  "Dub techno",
  "Hard techno",
  "Free tekno",
  "Jungletek",
  "Raggatek",
  "Industrial techno",
  "Minimal techno",
  "Schaffel",
  "Toytown techno",
  "Trance music",
  "Acid trance",
  "Balearic trance",
  "Dream trance",
  "Eurotrance",
  "Hands up",
  "Goa trance",
  "Nitzhonot",
  "Hard trance",
  "Progressive trance",
  "Psychedelic trance",
  "Dark psytrance",
  "Full-on",
  "Minimal psytrance",
  "Progressive psytrance",
  "Suomisaundi",
  "Tech trance",
  "Uplifting trance",
  "Vocal trance",
  "UK garage",
  "2-step garage",
  "Bassline",
  "Breakstep",
  "Dubstep",
  "Brostep",
  "Post-dubstep",
  "Reggaestep",
  "Riddim",
  "Future garage",
  "Grime",
  "Grindie",
  "Speed garage",
  "UK funky",
  "Funkstep",
  "Wonky",
  "Video game music",
  "Chiptune",
  "Bitpop",
  "Skweee",
  "Nintendocore",
  "FM synthesis",
  "Sequencer music",
  "Avant-garde electronic",
  "Experimental hip hop",
  "Hyperspeed",
  "Dark pop",
  "Bedroom pop",
  "Indie pop",
  "Art pop",
  "Jazz rap",
  "Boom bap",
  "Trap soul",
  "Lo-fi trap",
  "New wave trap",
  "Tech-funk",
  "Electro-techno",
  "Deep tech-house",
  "Melodic techno",
  "Synthcore",
  "Harsh electro",
  "Witchtrap",
  "Hypergrunge",
  "Future glitch",
  "Vaportrap"
]
